version: 2

project_name: uproc.cli

before:
  hooks:
    - go mod tidy

builds:
  - id: uproc
    binary: uproc
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - id: default
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

changelog:
  use: git
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: uproc-io
    name: uproc.cli
  draft: false
  prerelease: auto

brews:
  - name: uproc
    repository:
      owner: uproc-io
      name: homebrew-uproc
    homepage: https://github.com/uproc-io/uproc.cli
    description: Uproc CLI
    test: |
      system "#{bin}/uproc --help"
    install: |
      bin.install "uproc"

scoops:
  - name: uproc
    repository:
      owner: uproc-io
      name: scoop-bucket
      branch: main
      token: "{{ .Env.GITHUB_TOKEN }}"
    commit_author:
      name: github-actions[bot]
      email: 41898282+github-actions[bot]@users.noreply.github.com
    homepage: https://github.com/uproc-io/uproc.cli
    description: Uproc CLI
    license: Proprietary
